### ISSUE TITLE
[Bug] Unknown validation rule `not_empty`

### ISSUE THREAD

**Issue by AlexandreBrg** [greyblake/nutype#15]
## Context 

Hello! I've created a brand new project, and tried to use nutype in it, but faced an issue when trying to use validators 

## Problem

I've created a brand new project (with `cargo new my-crate --lib`), and added `nutype=0.1.1` dependency, and tried the following piece of code:

```rust
// lib.rs
pub mod video {
    use nutype::nutype;

    #[nutype(
        sanitize(trim)
        validate(min_length = 1, max_length = 100)
    )]
    pub struct VideoTitle(String);
}
```

This piece of code generates the following error:

```
error: Unknown validation rule `min_length`
 --> lib/my-crate/src/lib.rs:6:18
  |
6 |         validate(min_length = 1, max_length = 100)
  |                  ^^^^^^^^^^
```

This error is also reached when using any other validator (`not_empty`...)

## Additional information

Cargo version: 1.66.1
Nutype version: 0.1.1

**Comment by greyblake** [comment]
@AlexandreBrg Hi, 
I am sorry you have to experience this.

You're using version 0.1.1 please review to the documentation of this particular version: https://docs.rs/nutype/0.1.1/nutype/

In that version the validator's name was `present`, but since many people reported that it was not clear what it does,  [we've renamed](https://github.com/greyblake/nutype/pull/8) it to `not_empty` (and yeah, we updated the README). But the new version is not yet released.

I am gonna close the issue. If you run into something else please feel free to open a new issue.

Thanks for giving `nutype`  a try!

**Comment by greyblake** [comment]
> validate(min_length = 1, max_length = 100)

Sorry, I missed it.
The validator's name is **min_len** not `min_length`. This was not changed.
