### ISSUE TITLE
Following type does not work

### ISSUE THREAD

**Issue by hernangonzalez** [greyblake/nutype#4]
Hi, nice crate!

I tried to use it with something like:
MyRequest(http::Request<Option<Bytes>>)

And build failed with an unsupported message. Is that right?

Thanks,
H.

**Comment by greyblake** [comment]
@hernangonzalez 

Hi, thanks for your feedback!
The reason it does not work (yet), because nutype at the moment can be applied only on a predefined set of types (integers, floats and `String`). For more info on that please see [Inner Types](https://github.com/greyblake/nutype#inner-types) section in the readme.

However, I guess it must be possible to allow custom sanitizers and validators even for other types.

I have opened another issue for this https://github.com/greyblake/nutype/issues/7.
I am gonna close this one.
